name: Java CI with Gradle and Docker Build/Push

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ main ]

permissions:
  contents: read
  packages: write

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Code
      uses: actions/checkout@v2

    - name: Set up JDK 11 with Gradle
      uses: actions/setup-java@v1
      with:
        java-version: 11
        distribution: 'adopt'
        gradle-version: 7.0.2

    - name: Build with Gradle
      run: |
        ./gradlew build --no-daemon --stacktrace

    - name: Configure Docker
      uses: docker/setup-buildx-action@v1

    - name: Build and Push Docker Image
      uses: docker/build-push-action@v2
      with:
        context: .
        push: true
        tags: eechukwu/demo-apps:${{ github.sha }}
